export * as authApi from "./auth";
export * as userApi from "./user";
export * as generalApi from "./general";
export * as mediaApi from "./media";
export * as customerApi from "./customer";
export * as buildingApi from "./building";
export * as complexApi from "./complex";
export * as roleApi from "./role";
export * as otpApi from "./otp";
export * as adApi from "./ad";
export * as entranceApi from "./entrance";
export * as townApi from "./town"